"""stok_yonetim: sonradan_eklendi + cikis + zimmet

Revision ID: 95ea12a6d455
Revises: dbc4f2d9c299
Create Date: 2026-05-26 19:01:49.156545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95ea12a6d455'
down_revision: Union[str, None] = 'dbc4f2d9c299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seriler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sonradan_eklendi', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('cikis_zaman', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cikis_kullanici_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cikis_notu', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('zimmet_kullanici_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zimmet_zaman', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('zimmet_notu', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_seri_cikis_kullanici', 'users', ['cikis_kullanici_id'], ['id'])
        batch_op.create_foreign_key('fk_seri_zimmet_kullanici', 'users', ['zimmet_kullanici_id'], ['id'])

    with op.batch_alter_table('stoklar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sonradan_eklendi', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stoklar', schema=None) as batch_op:
        batch_op.drop_column('sonradan_eklendi')

    with op.batch_alter_table('seriler', schema=None) as batch_op:
        batch_op.drop_constraint('fk_seri_zimmet_kullanici', type_='foreignkey')
        batch_op.drop_constraint('fk_seri_cikis_kullanici', type_='foreignkey')
        batch_op.drop_column('zimmet_notu')
        batch_op.drop_column('zimmet_zaman')
        batch_op.drop_column('zimmet_kullanici_id')
        batch_op.drop_column('cikis_notu')
        batch_op.drop_column('cikis_kullanici_id')
        batch_op.drop_column('cikis_zaman')
        batch_op.drop_column('sonradan_eklendi')

    # ### end Alembic commands ###
