"""initial

Revision ID: dbc4f2d9c299
Revises: 
Create Date: 2026-05-26 18:07:54.116942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbc4f2d9c299'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_denemeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('basarili', sa.Boolean(), nullable=False),
    sa.Column('zaman', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_denemeleri', schema=None) as batch_op:
        batch_op.create_index('ix_login_ad_zaman', ['ad', 'zaman'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=80), nullable=False),
    sa.Column('pin_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('olusturma', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_loglari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zaman', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('kullanici_ad', sa.String(length=80), nullable=True),
    sa.Column('eylem', sa.String(length=60), nullable=False),
    sa.Column('kaynak_tip', sa.String(length=40), nullable=True),
    sa.Column('kaynak_id', sa.String(length=40), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detay', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_loglari', schema=None) as batch_op:
        batch_op.create_index('ix_audit_kullanici', ['kullanici_id'], unique=False)
        batch_op.create_index('ix_audit_zaman', ['zaman'], unique=False)

    op.create_table('sayim_oturumlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=120), nullable=False),
    sa.Column('lokasyon', sa.String(length=80), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('baslangic', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('bitis', sa.DateTime(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stoklar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oturum_id', sa.Integer(), nullable=False),
    sa.Column('stok_kodu', sa.String(length=80), nullable=False),
    sa.Column('urun_adi', sa.String(length=200), nullable=False),
    sa.Column('portal_sayim', sa.Integer(), nullable=False),
    sa.Column('olusturma', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['oturum_id'], ['sayim_oturumlari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oturum_id', 'stok_kodu', name='uq_stok_oturum_kod')
    )
    with op.batch_alter_table('stoklar', schema=None) as batch_op:
        batch_op.create_index('ix_stok_oturum', ['oturum_id'], unique=False)

    op.create_table('tarama_loglari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oturum_id', sa.Integer(), nullable=False),
    sa.Column('zaman', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('seri_giris', sa.String(length=160), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('stok_kodu', sa.String(length=80), nullable=True),
    sa.Column('urun_adi', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['oturum_id'], ['sayim_oturumlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarama_loglari', schema=None) as batch_op:
        batch_op.create_index('ix_log_oturum_zaman', ['oturum_id', 'zaman'], unique=False)

    op.create_table('seriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oturum_id', sa.Integer(), nullable=False),
    sa.Column('stok_id', sa.Integer(), nullable=False),
    sa.Column('seri_no', sa.String(length=120), nullable=False),
    sa.Column('seri_no_norm', sa.String(length=120), nullable=False),
    sa.Column('sayildi', sa.Boolean(), nullable=False),
    sa.Column('sayim_tarihi', sa.DateTime(), nullable=True),
    sa.Column('sayan_id', sa.Integer(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['oturum_id'], ['sayim_oturumlari.id'], ),
    sa.ForeignKeyConstraint(['sayan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stok_id'], ['stoklar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oturum_id', 'stok_id', 'seri_no', name='uq_seri_oturum_stok_no')
    )
    with op.batch_alter_table('seriler', schema=None) as batch_op:
        batch_op.create_index('ix_seri_oturum_norm', ['oturum_id', 'seri_no_norm'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seriler', schema=None) as batch_op:
        batch_op.drop_index('ix_seri_oturum_norm')

    op.drop_table('seriler')
    with op.batch_alter_table('tarama_loglari', schema=None) as batch_op:
        batch_op.drop_index('ix_log_oturum_zaman')

    op.drop_table('tarama_loglari')
    with op.batch_alter_table('stoklar', schema=None) as batch_op:
        batch_op.drop_index('ix_stok_oturum')

    op.drop_table('stoklar')
    op.drop_table('sayim_oturumlari')
    with op.batch_alter_table('audit_loglari', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_zaman')
        batch_op.drop_index('ix_audit_kullanici')

    op.drop_table('audit_loglari')
    op.drop_table('users')
    with op.batch_alter_table('login_denemeleri', schema=None) as batch_op:
        batch_op.drop_index('ix_login_ad_zaman')

    op.drop_table('login_denemeleri')
    # ### end Alembic commands ###
